[project]
name = "sewer-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "basedpyright>=1.32.1",
    "ruff>=0.14.2",
]

[tool.basedpyright]
